services:
  db:
    image: mysql:8.0
    container_name: elotus-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: elotus
      MYSQL_USER: elotus_user
      MYSQL_PASSWORD: elotus_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  server:
    build: .
    container_name: elotus-server
    restart: always
    ports:
      - "8081:8080"
    volumes:
      - ./:/app
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: elotus_user
      DB_PASSWORD: elotus_password
      DB_NAME: elotus
      JWT_SECRET: supersecretkey
    depends_on:
      - db

volumes:
  db_data:
